language: objective-c
cache:
  - bundler
  - cocoapods
before_install:
  - pod repo update > /dev/null
install:
  - bundle install
  - bundle update
  - bundle exec pod install
script:
  - fastlane test